---
title: "elk"
format: html
---

```{r}
library(tidyverse)
library(sf)
library(terra)
library(tmap)
library(patchwork)
```


```{r}
magpie <- read_csv(here::here("data", "magpie_obvs.csv"))
tule_elk <- read_csv(here::here("data", "tule_elk_obvs.csv"))

bioclim_dir <- here::here("data", "climate", "wc2.1_2.5m")
bioclim <- list.files(bioclim_dir, pattern = glob2rx("*.tif$"), full.names = TRUE)
bioclim_sort <- bioclim[
  # Sort filepaths based on numeric suffix
  order(
    # Extract numeric suffix of filenames and convert to numeric
    as.numeric(gsub(".*_(\\d+)\\.tif$", "\\1", bioclim))
    )
  ]
bioclim_rast <- rast(bioclim_sort)
```

# 2. 

```{r}
# Rename raster layers
variables <- c("annualMeanTemp", "meanDiurnalRange", "isothermality", "tempSeasonality", "maxTempWarmMonth", "maxTempColdMonth", "tempAnnualRange", "meanTempWetQ", "meanTempDryQ", "meanTempWarmQ", "meanTempColdQ", "annualPrecip", "precipWetMonth", "precipDryMonth", "precipSeasonality", "precipWetQ", "precipDryQ", "precipWarmQ", "precipColdQ")
names(bioclim_rast) <- variables
```

## 3.

```{r}
magpie_sf <- magpie |> 
  rename(long = longitude,
         lat = latitude) |> 
  drop_na(long, lat) |> 
  st_as_sf(coords = c("long", "lat"), crs = 4326)

magpie_bbox <- st_bbox(magpie_sf)

bioclim_crop <- crop(bioclim_rast, magpie_sf)
```

## 4.

```{r}
extracted <- tibble(terra::extract(bioclim_crop, magpie_sf))
```

## 5. 

```{r}
# Generate random sample points from raster
random_pts <- spatSample(bioclim_crop[["annualMeanTemp"]],
                         na.rm = TRUE, # Random sample non-NA cells
                         size = (nrow(magpie) * 2), # Sample size
                         as.points = TRUE) |> # Return SpatVector
  st_as_sf()

# Extract points from raster for background values
bioClim_random_pts <- as_tibble(terra::extract(bioclim_crop, random_pts))
```

## 6.

```{r}
tm_shape(bioclim_crop[["annualPrecip"]]) +
  tm_raster(col.scale = tm_scale_continuous(values = "Blues")) +
tm_shape(magpie_sf) +
  tm_dots(size = 0.1)

tm_shape(bioclim_crop[["annualMeanTemp"]]) +
  tm_raster(col.scale = tm_scale_continuous(values = "Oranges")) +
tm_shape(magpie_sf) +
  tm_dots(size = 0.1)

ggplot(data = extracted, aes(x = annualPrecip, y = annualMeanTemp)) +
  geom_point(shape = 16, color = "#3a5a40") +
  labs(x = "Annual precipitation",
       y = "Annual mean temperature", 
       title = "Species climate niche") +
  theme_bw()

ggplot(data = bioClim_random_pts, aes(x = annualPrecip, y = annualMeanTemp)) +
  geom_point(shape = 16) +
  labs(x = "Annual precipitation",
       y = element_blank(), 
       title = "Background climate") +
  theme_bw()

#plot_1 + plot_2
```

## 7.

```{r}
climate_envelope <- function(clim_rast, clim_var1, clim_var2, occurence, species_name) {
  
  # Convert species_name
  clean_species_name <- species_name |> 
    str_to_lower() |> 
    str_replace(" ", "_")
  
  # Get occurrences
  occur_sf <- occurence |> 
    rename(long = longitude,
           lat = latitude) |> 
    drop_na(long, lat) |> 
    st_as_sf(coords = c("long", "lat"), crs = 4326)
  
  # Get occurrences bbox
  occur_bbox <- st_bbox(occur_sf)
  
  # Crop climate raster
  clim_crop <- crop(clim_rast, occur_bbox)
  
  #Extract raster cells
  extracted <- tibble(terra::extract(clim_crop, occur_sf))
  

  random_pts <- spatSample(clim_crop[[clim_var1]],
                         na.rm = TRUE, # Random sample non-NA cells
                         size = (nrow(occurence) * 2), # Sample size
                         as.points = TRUE) |> # Return SpatVector
  st_as_sf()

  # Extract points from raster for background values
  clim_random_pts <- as_tibble(terra::extract(clim_crop, random_pts))

  map1 <- tm_shape(clim_crop[[clim_var1]]) +
    tm_raster(col.scale = tm_scale_continuous(values = "Blues"),
              col.legend = tm_legend(title = clim_var1))
  map2 <- tm_shape(clim_crop[[clim_var2]]) +
    tm_raster(col.scale = tm_scale_continuous(values = "Oranges"),
              col.legend = tm_legend(title = clim_var2))

  tmap_arrange(map1, map2, ncol = 2)

}
```

```{r}
climate_envelope(bioclim_rast, "annualPrecip", "annualMeanTemp", tule_elk, "Tule Elk")
```

