---
title: "easter_island"
format: html
---

```{r}
library(here)
library(tidyverse)
library(sf)
library(stars)
library(tmap)
```

# 1. Load in data
```{r}
ei_points <- st_read(here("data", "easter-island", "ei_points.gpkg")) |> 
  filter(type == "volcano")
ei_elev <- read_stars(here("data", "easter-island", "ei_elev.tif"))
ei_borders <- st_read(here("data", "easter-island", "ei_border.gpkg"))
ei_roads <- st_read(here("data", "easter-island", "ei_roads.gpkg"))
```

# 2. Create easter island
```{r}
tm_shape(ei_borders) +
  tm_borders() +
  tm_title("Dat Rapa Nui")
```

# 3. Create easter island + more
```{r}
tmap_mode('plot')

tm_shape(ei_borders) +
  tm_borders(lwd = 5) +
tm_shape(ei_elev) +
  tm_raster(col.scale = tm_scale_continuous(values = 'brewer.greens'),
            col.legend = tm_legend(title = "Elevation (m)", 
                                   reverse = TRUE,
                                   position = c('bottom', 'right'))) +
tm_shape(ei_roads) +
  tm_lines(col = 'orange') +
tm_shape(ei_points) +
  tm_symbols(shape = 23, size = 0.4, fill = "red") +
tm_title(text = "Rapa Nui Details") +
tm_compass(position = 'top') +
tm_scalebar(position = 'top')


```

# 4. Interactive
```{r}
tmap_mode("view")
```

