---
title: "raster_vectors"
format: html
---

```{r}
library(tidyverse)
library(sf)
library(terra)
library(spData)
```

```{r}
# Load data
nz_height <- nz_height
grain <- terra::rast(system.file("raster/grain.tif", package = "spData"))
```

## 1.

```{r}
# Subset to points higher than 3100m
nz_height3100 <- nz_height |> 
  filter(elevation > 3100)
```

## 2.

```{r}
# Create template raster from nz_height
nz_template <- rast(ext(nz_height3100),
                    resolution = 3000,
                    crs = crs(nz_height3100))
```

## 3.

```{r}
# Rasterize vector points
nz_raster <- rasterize(nz_height3100, nz_template, fun = 'length') # Convert vector points to raster data
```

```{r}
# Plot data
plot(nz_raster, main = "Number of elevation points > 3100 in each cell")
plot(st_geometry(nz_height3100), add = TRUE)
```

## 4. 

```{r}
nz_raster2 <- rasterize(nz_height3100, nz_template, fun = max)

plot(nz_raster2, main = "Max elevation in each cell")
plot(st_geometry(nz_height3100), add = TRUE)
```

## 5. 

```{r}
nz_raster_low <- aggregate(nz_raster, fact = 2, 
                           fun = sum, na.rm = TRUE)

nz_resample <- resample(nz_raster_low, nz_raster)

plots <- c(nz_raster, nz_resample)
labs <- c("Original 3 x 3 km", "Resample 3 x 3 km")
plot(plots, main = labs)
```

```{r}
plot(nz_raster_low, main = "Resample 6 x 6 km")
```

## 6.

```{r}
# Plot grain raster
plot(grain, main = "Grain (Raster)")
```

```{r}
# Convert to vector
grain_poly <- as.polygons(grain) %>% 
  st_as_sf()

plot(grain_poly, main = "Grain (Vector)")
```

```{r}
# Plot only clay
grain_poly |> 
  filter(grain == 'clay') |> 
  plot(main = 'Clay')
```

